# Generated by Django 5.1.2 on 2024-10-20 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('crisisID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('severitylvl', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('currentstatus', models.CharField(choices=[('R', 'Reported'), ('I', 'In Progress'), ('S', 'Solved')], max_length=1)),
            ],
        ),
    ]
