# Generated by Django 5.1.2 on 2024-11-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_volunteer_skills_delete_skill_and_more'),
        ('report', '0002_alter_crisis_lat_alter_crisis_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.organization'),
        ),
    ]
