# Generated by Django 5.1.2 on 2024-11-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
    ]
