# Generated by Django 5.1.2 on 2024-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_volunteer_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
