# Generated by Django 5.1.2 on 2024-11-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_volunteer_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
        ),
    ]
