# Generated by Django 5.1.2 on 2024-11-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_task'),
        ('report', '0003_crisis_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crisis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='report.crisis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.volunteer'),
        ),
    ]
