# Generated by Django 5.1.2 on 2024-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_task_crisis_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('I', 'In Progress'), ('S', 'Solved')], default='U', max_length=1),
        ),
    ]
