# Generated by Django 5.1.2 on 2024-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('I', 'In Progress'), ('S', 'Solved')], default='Unsolved', max_length=1),
        ),
    ]
