# Generated by Django 5.1.2 on 2024-11-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_task_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='ward',
        ),
    ]
